services:
  - type: web
    name: orient-ecommerce
    runtime: python
    region: singapore
    plan: free
    buildCommand: bash build.sh
    initialDeployHook: python manage.py seed_data
    startCommand: gunicorn orient.wsgi:application
    healthCheckPath: /health/
    autoDeployTrigger: commit
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: orient-postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@orientcomputers.com.bd
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false

databases:
  - name: orient-postgres
    region: singapore
    plan: free
    postgresMajorVersion: "18"
    ipAllowList: []
