# Generated by Django 4.2.30 on 2026-08-31 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='off_day',
            field=models.CharField(default='Friday', help_text='Weekly Holiday', max_length=50),
        ),
        migrations.AlterField(
            model_name='branch',
            name='hours',
            field=models.CharField(default='Sat–Thu: 10am – 8pm', max_length=100),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
