# Generated by Django 4.2.30 on 2026-08-31 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productimage_image_url_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('logo_url', models.URLField(blank=True, help_text='Online logo image URL', max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='is_call_for_price',
            field=models.BooleanField(default=False, help_text='Mark True for enterprise hardware where price is on quotation'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_upcoming',
            field=models.BooleanField(default=False, help_text='Preview item coming soon'),
        ),
    ]
